### ISSUE TITLE
在config.ts中使用报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-plugin-ga#3]
![image](https://user-images.githubusercontent.com/11746742/53478978-06412380-3ab3-11e9-8c16-2490b66b4f92.png)

直接在pro项目中把config.js 修改为config.ts重现

**Comment by imhele** [comment]
这是 TypeScript 的规则，从 umi-types 引用 `IPlugin` ，把 `const plugins` 改成 `const plugins: IPlugin[]` 即可

**Comment by xiaohuoni** [comment]
我好奇的是这个提示的代码是在哪里？

**Comment by imhele** [comment]
config.ts  里面有一句 `plugins.push()` ，由于定义 `plugins` 时没有为它指定类型，TypeScript 会自动从值中探测类型

**Comment by xiaohuoni** [comment]
学习了
